DemoSolution/DemoProject/Entities/Actor.cs
namespace DemoProject.Entities;

public class Actor
{
    public string Name { get; set; }

    public List<Movie> Movies { get; set; } = new();
}

DemoSolution/DemoProject/Entities/Car.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DemoProject.Entities;

public class Car
{
    // data annotations validation

    public int Id { get; set; }

    [RegularExpression("^[a-zA-Z -]+$", ErrorMessage = "Alleen letters en spaties graag")]
    public required string Make { get; set; }

    public required string Model { get; set; }

    public required int Year { get; set; }

    public required string PhotoUrl { get; set; }

    public required CarType Type { get; set; } // gebruik ik voor display purposes

    [DisplayName("Type hier")]
    public required int TypeId { get; set; } // gebruik ik voor het toevoegen/wijzigen
}

DemoSolution/DemoProject/Entities/CarType.cs
using System.Text.Json.Serialization;

namespace DemoProject.Entities;

public class CarType
{
    public required int Id { get; set; }

    public required string Name { get; set; }

    [JsonIgnore]
    public IEnumerable<Car> Cars { get; set; }
}

DemoSolution/DemoProject/Entities/Movie.cs
using System.Text.Json.Serialization;

namespace DemoProject.Entities;

public class Movie
{
    public string Title { get; set; }

    public List<Actor> Actors { get; set; } = new();
}

DemoSolution/DemoProject/Controllers/CarController.cs
using DemoShared.Dtos;
using DemoShared.Entities;
using DemoProject.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace DemoProject.Controllers;

[Route("api/[controller]")]
[ApiController] // ModelState.IsValid  [FromBody]
public class CarController : ControllerBase
{
    private readonly ICarRepository _carRepository;

    public CarController(ICarRepository carRepository)
    {
        _carRepository = carRepository;
    }

    [HttpGet]
    public async Task<CarGetAllResponseDto> GetAll()
    {
        var cars = await _carRepository.GetAllAsync();
        return new() { Cars = cars.Select(c => c.ToDto()) }; // mapping car entities => car dtos
    }

    [HttpGet("{id:min(1)}")]
    public async Task<ActionResult<Car>> Get(int id)
    {
        var car = await _carRepository.GetAsync(id);
        return car != null ? car : NotFound($"ID {id} does not exist");
    }

    [HttpPost]
    public async Task<ActionResult<Car>> Post(Car newCar)
    {
        await _carRepository.AddAsync(newCar);
        return CreatedAtAction(nameof(Get), new { id = newCar.Id }, newCar);
    }

    [HttpPatch("{id:int}")]
    public async Task<ActionResult<CarPatchResponseDto>> Patch(int id, CarPatchRequestDto dto)
    {
        if (!await _carRepository.ExistsAsync(id))
        {
            return NotFound($"ID {id} was not found");
        }

        var updatedCar = await _carRepository.UpdatePhotoAsync(id, dto.PhotoUrl);
        return new CarPatchResponseDto(UpdatedCar: updatedCar.ToDto());
    }
}

DemoSolution/DemoProject/Controllers/MovieController.cs
using DemoShared.Entities;
using Microsoft.AspNetCore.Mvc;

namespace DemoProject.Controllers;

[Route("api/movies")]
public class MovieController
{
    public IEnumerable<Movie> Get()
    {
        var fastAndFuriousTokyo = new Movie { Title = "Fast and Furious: Tokyo Drift" };
        var shawshank = new Movie { Title = "The Shawshank Redemption" };
        var bruceAlmighty = new Movie { Title = "Bruce Almighty" };

        var vinny = new Actor { Name = "Vinny Diesel" };
        var morgan = new Actor { Name = "Morgan Freeman" };
        var nat = new Actor { Name = "Nat" };

        fastAndFuriousTokyo.Actors.Add(vinny);
        fastAndFuriousTokyo.Actors.Add(nat);
        shawshank.Actors.Add(morgan);
        bruceAlmighty.Actors.Add(morgan);

        vinny.Movies.Add(fastAndFuriousTokyo);
        nat.Movies.Add(fastAndFuriousTokyo);
        morgan.Movies.Add(shawshank);
        morgan.Movies.Add(bruceAlmighty);

        var movies = new List<Movie> { fastAndFuriousTokyo, shawshank, bruceAlmighty };
        //movies.SelectMany(x => x.Actors).ToList().ForEach(a => a.Movies = null);
        return movies;

    }
}

DemoSolution/DemoProject/Pages/Auth.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoProject.Pages;

public class Auth : PageModel
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly SignInManager<IdentityUser> _signInManager;
    public string Status { get; set; }

    public Auth(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
    {
        _userManager = userManager;
        _signInManager = signInManager;
    }

    public async Task OnGetRegister()
    {
        var jef = new IdentityUser
        {
            UserName = "Jef",
            Email = "jef@familievanjef.be"
        };
        var result = await _userManager.CreateAsync(jef, "Jef123!");
        if (result.Succeeded)
        {
            Status = "Yes! Geregistreerd!";
        }
        else
        {
            Status = $"Kon niet registreren: {string.Join(", ", result.Errors.Select(x => x.Description))}";
        }
    }
    
    public async Task OnGetLogin()
    {
        var result = await _signInManager.PasswordSignInAsync("Jef", "Jef123!", false, false);
        if (result.Succeeded)
        {
            Status = "Ingelogd!";
        }
        else
        {
            Status = $"Kon niet inloggen: {result.IsLockedOut} | {result.IsNotAllowed} | {result.RequiresTwoFactor}";
        }
    }
    
    public async Task OnGetLogout()
    {
        await _signInManager.SignOutAsync();
        Status = "Uitgelogd!";
    }
    
    public async Task OnGetDoNothing()
    {
        
    }
}

DemoSolution/DemoProject/Pages/CarDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoProject.Pages;

public class CarDetailsModel : PageModel
{
    public void OnGet(int id)
    {
        Console.WriteLine("Car details id: " + id);

        Console.WriteLine(Request.Query["hoi"]);
    }
}

DemoSolution/DemoProject/Pages/Fout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoProject.Pages
{
    public class FoutModel : PageModel
    {
        public void OnGet()
        {
            throw new NotImplementedException("Ga weg");
        }
    }
}

DemoSolution/DemoProject/Pages/Index.cshtml.cs
using DemoShared.Entities;
using DemoProject.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DemoProject.Pages;

public class IndexModel : PageModel // bij ieder request wordt deze opnieuw geinstantieerd
{
    public string Bla { get; set; } = "Hey daar!";

    public List<Car> Cars { get; set; } = default!;
    public List<CarType> CarTypes { get; set; } = default!;

    [BindProperty]
    public Car NewCar { get; set; } = default!;

    private readonly ICarRepository _carRepository;
    private readonly ICarTypeRepository _carTypeRepository;

    public IndexModel(ICarRepository carRepository, ICarTypeRepository carTypeRepository)
    {
        _carRepository = carRepository;
        _carTypeRepository = carTypeRepository;
    }

    public async Task OnGet()
    {
        Cars = (await _carRepository.GetAllAsync()).ToList();
        CarTypes = (await _carTypeRepository.GetAllAsync()).ToList();
    }

    // page handlers

    public async Task<IActionResult> OnPost() // model binding  reflection
    {
        if (!ModelState.IsValid)
        {
            Console.WriteLine("dat is NIET valid");
            Cars = (await _carRepository.GetAllAsync()).ToList();
            CarTypes = (await _carTypeRepository.GetAllAsync()).ToList();
            return Page();
        }

        await _carRepository.AddAsync(NewCar);
        return RedirectToPage();
    }
}

DemoSolution/DemoProject/Pages/Tweede.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DemoProject.Pages
{
    public class TweedeModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

DemoSolution/DemoProject/Pages/Auth.cshtml
@page
@model Auth

@section title { Auth }

<p>Status: @Model.Status</p>

@if (User.Identity.IsAuthenticated)
{
    <p>Ingelogd als @User.Identity.Name</p>
}
else
{
    <p>Niet ingelogd.</p>
}

<a asp-page-handler="register">Register</a> |
<a asp-page-handler="login">Inloggen</a> |
<a asp-page-handler="logout">Uitloggen</a> |
<a asp-page-handler="do-nothing">Doe niks</a>

DemoSolution/DemoProject/Pages/CarDetails.cshtml
@page "{id:int:min(5000)}"
@model CarDetailsModel

@section title { Car details }

Hallo vanaf details

DemoSolution/DemoProject/Pages/Fout.cshtml
@page
@model DemoProject.Pages.FoutModel
@{
}

DemoSolution/DemoProject/Pages/Index.cshtml
@page
@model IndexModel

@section title { Cars }

@section css {
    <link rel="stylesheet" href="bla.css" />
}

<h1>Cars</h1>

<div class="flex">
    <form method="post">
        <ol>
            <li>
                <label for="input-make">Make:</label>
                <input id="input-make" asp-for="NewCar.Make" />
                <span asp-validation-for="NewCar.Make"></span>
            </li>
            <li>
                <label for="input-model">Model:</label>
                <input id="input-model" asp-for="NewCar.Model" />
                <span asp-validation-for="NewCar.Model"></span>
            </li>
            <li>
                <label asp-for="NewCar.TypeId"></label>
                <select id="input-type" asp-for="NewCar.TypeId" asp-items="@(new SelectList(Model.CarTypes, "Id", "Name"))"></select>
                <span asp-validation-for="NewCar.TypeId"></span>
            </li>
            <li>
                <label for="input-year">Year of build:</label>
                <input id="input-year" asp-for="NewCar.Year" />
                <span asp-validation-for="NewCar.Year"></span>
            </li>
            <li>
                <label for="input-photo-url">Photo URL:</label>
                <input id="input-photo-url" asp-for="NewCar.PhotoUrl" />
                <span asp-validation-for="NewCar.PhotoUrl"></span>
            </li>
            <li>
                @* <input type="submit" value="Submit" /> *@
                <button>
                    Submit
                    <img />
                </button>
            </li>
        </ol>
    </form>

    @if (Model.Cars == null || !Model.Cars.Any())
    {
        <p>Geen auto's vandaag.</p>
        return;
    }

    <table>
        <thead>
            <tr>
                <th>Make</th>
                <th>Model</th>
                <th>Type</th>
                <th>Year of build</th>
                <th>Photo</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var car in Model.Cars)
            {
                <tr class="@(car.Year < 2000 ? "oud" : "")">
                    <td>@car.Make</td>
                    <td>@car.Model</td>
                    <td>@car.Type.Name</td>
                    <td><partial name="_OldCarDescriptor" model="car.Year" /></td>
                    <td><img src="@car.PhotoUrl"></td>
                </tr>
            }
        </tbody>
    </table>
</div>

DemoSolution/DemoProject/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>@RenderSection("title") - beste webapp aller tijden</title>
    @RenderSection("css", false)
    @RenderSection("scripts", false)
</head>

<body>
    <header>
        Beste demoapp aller tijden

        <nav>
            <ol>
                <li><a href="/">Cars</a></li>
                <li><a href="/tweede">Tweede</a></li>
                <li><a href="/auth">Auth</a></li>
                <li><a href="/cardetails/bla">Cardetails/bla</a></li>
                <li><a href="/cardetails/bla?hoi=iets&wat=dus">Cardetails/bla?hoi=iets&wat=dus</a></li>
            </ol>
        </nav>
    </header>

    @RenderBody()

    <footer>&copy; JP 2k24</footer>
</body>
</html>

DemoSolution/DemoProject/Pages/Shared/_OldCarDescriptor.cshtml
@model int

@if (Model < 1960)
{
    <text>Klassieker</text>
}
else if (Model >= 1960 && Model < 1990)
{
    <text>Oud barrel</text>
}
else
{
    <text>Hippe bak</text>
}

DemoSolution/DemoProject/Pages/Tweede.cshtml
@page
@model TweedeModel

@section title { Tweede }


<h1>Iets anders</h1>

Hallo vanaf tweede pagina